logging:
  level:
    web: DEBUG
spring:
  main: 
    banner-mode: off
  neo4j:
    authentication:
      username: neo4j
    uri: bolt://localhost:7687
  profiles:
    active: local, dev, qa, prod, test