server:
  port: 7005
spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:7005
          service-base-url: http://localhost:7005
        url: http://localhost:9000
  neo4j:
    authentication:
      password: 31A1fZZHynvY&mU%
management:
  info:
    git:
      enabled: true
      mode: full
  endpoint:
    env:
      show-values: always
logging:
  level:
    root: INFO