info:
  author: chemch
logging:
  level:
    web: WARN
spring:
  main: 
    banner-mode: off
  neo4j:
    authentication:
      username: neo4j
    uri: bolt://localhost:7687
  profiles:
    active: local, dev, qa, prod, test
management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'