server:
  port: 13002
spring:
  boot:
    admin:
      client:
        url: http://localhost:9000
  neo4j:
    authentication:
      password: 9Dmt4&8EwC2*LQ9A
management:
  endpoint:
    env:
      show-values: always 