server:
  port: 12002
spring:
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:${server.port}
          service-base-url: http://localhost:${server.port}
        url: http://localhost:12000
  neo4j:
    authentication:
      password: 31A1fZZHynvY&mU%
management:
  info:
    git:
      enabled: true
      mode: full
  endpoint:
    env:
      show-values: always
logging:
  level:
    root: INFO